// Global handler for all uncaught exception or synchronous error
process.on('uncaughtException', (err) => {
  console.log(err.name, err.message);
  console.log('UNCAUGHT EXCEPTION! ðŸ’¥ Shutting down...');
  process.exit(1);
});
